services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: web_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  postgres:
    environment:
      POSTGRES_DB: web_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d web_db" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - postgres-data-dev:/var/lib/postgresql
      - ./docker-config/database/init.sh:/docker-entrypoint-initdb.d/init.sh

  adminer:
    image: adminer:latest
    container_name: web-db-adminer
    ports:
      - "8888:8080"
    depends_on:
      - postgres

volumes:
  postgres-data-dev: