services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always

  postgres:
    env_file:
      - .env.prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
    volumes:
      - postgres-data-prod:/var/lib/postgresql
      - ./docker-config/database/init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  postgres-data-prod: