spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:web_db}?reWriteBatchedInserts=true
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update # Cuando se use Flyway, cambiar a 'none'
    show-sql: true

  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true

api:
  docs:
    enabled: true
    title: Web API Documentation
    description: API documentation for the Web application.
    version: 1.0.0
    contact:
      name: Angel Torcal Catalán
      email: angeltorcalcatalan@gmail.com
      url: https://github.com/Chuckytin
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0
    servers:
      url: http://localhost:8080
      description: API server for local development

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
    tags:
      application: web
      environment: dev

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.springboot.web: DEBUG